version: '3'
services:
  mongodb:
    image: mongo
    container_name: tracking-mongodb
    volumes:
      - mongodb:/data/db
      - mongodb_config:/data/configdb
    ports:
        - 27017:27017
    command: mongod

volumes:
  mongodb:
  mongodb_config: